name: dropbot

# NOTE: These plugins are only used for development purposes
plugins:
  - name: vyper
  - name: foundry
  - name: alchemy

foundry:
  fork:
    ethereum:
      mainnet:
        upstream_provider: alchemy